In [55]:
#Import Dependencies
import os
import pandas as pd

In [56]:
#Path to Excel Sheets
path = "./Resources/DataBySchool"
pathCSV = "./Resources/DataBySchoolCSVs"

In [57]:
fileList = os.listdir(path)

In [58]:
for file in fileList:
    #Read in Excel File
    df = pd.read_excel(f'{path}/{file}')
    
    #Rename the new columns to be
    df.iloc[4,5] = f'{file[15:-4]}_{df.iloc[4,5]}'
    df.iloc[4,6] = f'{file[15:-4]}_{df.iloc[4,6]}'
    df.iloc[4,8] = f'YTD_{file[15:-4]}_{df.iloc[4,8]}'
    df.iloc[4,9] = f'YTD_{file[15:-4]}_{df.iloc[4,9]}'
    
    #Set column names to identified row
    df.columns = df.iloc[4]
    
    #Drop top of the data set
    df = df.drop([0,1,2,3,4])
    
    #Write new CSV files to CSV folder 
    df.to_csv(f'{pathCSV}/{file[15:-4]}.csv',index = False)

In [50]:
#df = pd.read_excel(f'{path}/{fileList[0]}')

In [51]:
#fileList[0]

'AppDatabySchool20062007Qtr1.xls'

In [52]:
#df.iloc[4,5] = f'{fileList[0][15:-4]}_{df.iloc[4,5]}'
#df.iloc[4,6] = f'{fileList[0][15:-4]}_{df.iloc[4,6]}'
#df.iloc[4,8] = f'YTD_{fileList[0][15:-4]}_{df.iloc[4,8]}'
#df.iloc[4,9] = f'YTD_{fileList[0][15:-4]}_{df.iloc[4,9]}'

In [53]:
#df.columns = df.iloc[4]
#df = df.drop([0,1,2,3,4])

4,OPE ID,School,State,Zip Code,School Type,20062007Qtr1_Dependent Students,20062007Qtr1_Independent Students,Quarterly Total,YTD_20062007Qtr1_Dependent Students,YTD_20062007Qtr1_Independent Students,Award Year To Date Total
5,00100200,ALABAMA AGRCLTL & MECHL UNIV,AL,35762-1357,Public,2502,961,3463,2502,961,3463
6,00100300,FAULKNER UNIVERSITY,AL,36109-3398,Private,301,603,904,301,603,904
7,00100400,UNIVERSITY OF MONTEVALLO,AL,35115-6000,Public,561,256,817,561,256,817
8,00100500,ALABAMA STATE UNIVERSITY,AL,36101-0000,Public,2845,1072,3917,2845,1072,3917
9,00100700,CENTRAL ALABAMA COMMUNITY COLLEGE,AL,35011-0000,Public,243,237,480,243,237,480
10,00100800,ATHENS STATE UNIVERSITY,AL,35611-1999,Public,137,581,718,137,581,718
11,00100900,AUBURN UNIVERSITY,AL,36849-5113,Public,6787,1901,8688,6787,1901,8688
12,00101200,BIRMINGHAM SOUTHERN COLLEGE,AL,35254-0002,Private,665,87,752,665,87,752
13,00101300,CALHOUN COMMUNITY COLLEGE,AL,35609-2216,Public,873,1211,2084,873,1211,2084
14,00101500,ENTERPRISE-OZARK COMMUNITY COLLEGE,AL,36331-1300,Public,159,192,351,159,192,351
15,00101600,UNIVERSITY OF NORTH ALABAMA,AL,35632-0001,Public,1140,517,1657,1140,517,1657
16,00101700,GADSDEN STATE COMMUNITY COLLEGE,AL,35903-2269,Public,490,570,1060,490,570,1060
17,00101706,GADSDEN STATE COMM. COLLEGE-AYERS CAMPUS,AL,36202-0000,Public,60,93,153,60,93,153
18,00101800,GEORGE C WALLACE COMMUNITY COLLEGE,AL,36303-0943,Public,234,390,624,234,390,624
19,00101900,HUNTINGDON COLLEGE,AL,36106-2148,Private,366,67,433,366,67,433
20,00102000,JACKSONVILLE STATE UNIVERSITY,AL,36265-1602,Public,1892,1193,3085,1892,1193,3085
21,00102100,JEFFERSON DAVIS COMMUNITY COLLEGE,AL,36427-2790,Public,83,154,237,83,154,237
22,00102200,JEFFERSON STATE COMMUNITY COLLEGE,AL,35215-3098,Public,531,948,1479,531,948,1479
23,00102300,JUDSON COLLEGE,AL,36756-2504,Private,85,29,114,85,29,114
24,00102400,UNIVERSITY OF WEST ALABAMA,AL,35470-0000,Public,606,560,1166,606,560,1166
25,00102600,MARION MILITARY INSTITUTE,AL,36756-3214,Public,34,4,38,34,4,38
26,00102800,MILES COLLEGE,AL,35064-2697,Private,467,211,678,467,211,678
27,00102900,UNIVERSITY OF MOBILE,AL,36613-0000,Private,378,434,812,378,434,812
28,00103000,BISHOP STATE COMMUNITY COLLEGE,AL,36603-5898,Public,275,796,1071,275,796,1071
29,00103001,BISHOP STATE COMM COLG-CARVER CMPS,AL,36617-0000,Public,19,39,58,19,39,58
30,00103002,BISHOP STAT COMM CLG-SW CMPS,AL,36605-0000,Public,13,21,34,13,21,34
31,00103100,NORTHEAST ALABAMA STATE CMNTY COLG,AL,35986-0159,Public,180,184,364,180,184,364
32,00103300,OAKWOOD COLLEGE,AL,35896-0001,Private,618,204,822,618,204,822
33,00103400,ALABAMA SOUTHERN COMMUNITY COLLEGE,AL,36460-5698,Public,141,117,258,141,117,258
34,00103600,SAMFORD UNIVERSITY,AL,35229-7000,Private,1743,1257,3000,1743,1257,3000
...,...,...,...,...,...,...,...,...,...,...,...
6873,03078300,VANCOUVER SCHOOL OF THEOLOGY,CN,00000-0000,Private,1,7,8,1,7,8
6874,03273300,CANADIAN COLLEGE OF NATUROPATHIC ME,CN,00000-0000,Private,3,9,12,3,9,12
6875,03298300,ALBERTA COLLEGE OF ART & DESIGN,CN,00000-0000,Public,11,1,12,11,1,12
6876,03332500,KWANTLEN UNIVERSITY COLLEGE,CN,00000-0000,Public,2,5,7,2,5,7
6877,03335400,CANADIAN UNIVERSITY COLLEGE,CN,00000-0000,Private,16,1,17,16,1,17
6878,03339300,ST. STEPHENS UNIVERSITY,CN,00000-0000,Private,1,1,2,1,1,2
6879,03348500,REDEEMER UNIVERSITY COLLEGE,CN,00000-0000,Private,13,1,14,13,1,14
6880,03408300,CANDIAN NAZARENE UNIVERSITY COLLEGE,CN,00000-0000,Private,3,1,4,3,1,4
6881,03421300,LOYALIST COLLEGE OF APPLIED ARTS &,CN,00000-0000,Public,1,1,2,1,1,2
6882,03433300,LANGARA COLLEGE,CN,00000-0000,Public,5,4,9,5,4,9
6883,03435400,ROYAL ROADS UNIVERSITY,CN,00000-0000,Public,1,2,3,1,2,3
6884,03511300,CN CLG ACUPUNCTURE & ORIENTAL MED,CN,00000-0000,Private,1,5,6,1,5,6
6885,03551300,INTERNATIONAL BIBLE COLLEGE,CN,00000-0000,Private,1,1,2,1,1,2
6886,03560400,NIAGARA COLLEGE-WELLAND CAMPUS,CN,00000-0000,Public,0,3,3,0,3,3
6887,03613300,UNIV OF NORTHERN BRITISH COLUMBIA,CN,00000-0000,Public,4,3,7,4,3,7
6888,03711300,CAPILANO UNIVERSITY,CN,00000-0000,Public,0,1,1,0,1,1
6889,03745300,BRITISH COLUMBIA INSTITUTE OF TECHNOLOGY,CN,00000-0000,Public,2,3,5,2,3,5
6890,00814700,UNIVERSIDAD AUTONOMA DE GUADALAJARA,MX,00000-0000,Private,19,358,377,19,358,377
6891,01041800,INST TEC Y DE ESTSUPER DE MONTERRE,MX,00000-0000,Private,25,21,46,25,21,46
6892,01067600,UNIVERSIDAD DE MONTERREY,MX,00000-0000,Private,5,9,14,5,9,14
6893,01093800,UNIVERSIDAD DE GUANAJUATO,MX,00000-0000,Public,7,9,16,7,9,16
6894,01097600,INSTITUTO ALLENDE,MX,00000-0000,Private,2,8,10,2,8,10
6895,01230100,UNIV AUTON DE TAMAULIPAS FAC DEMED,MX,00000-0000,Public,0,3,3,0,3,3
6896,02053300,CENTRO DE ESTUDIOS UNIVERSITARIOS D,MX,00000-0000,Private,12,29,41,12,29,41
6897,02283100,UNIVERSIDAD TECNOLOGICA DE MEXICO,MX,00000-0000,Proprietary,4,4,8,4,4,8
6898,01001000,AMERICAN SAMOA CMNTY COLLEGE,AS,96799-2609,Public,222,67,289,222,67,289
6899,01034300,COLLEGE OF MICRONESIA - FSM,FM,96941-0159,Public,276,48,324,276,48,324
6900,01100900,PALAU COMMUNITY COLLEGE,PW,96940-0009,Public,372,119,491,372,119,491
6901,03022400,COLLEGE OF THE MARSHALL ISLANDS,MH,96960-1258,Public,13,4,17,13,4,17
6902,03033000,NORTHERN MARIANAS COLLEGE,MP,96950-0000,Public,29,24,53,29,24,53